/**
 * Microphone capture + pitch AudioWorklet wiring.
 *
 * The worklet module is the esbuild bundle of pitch-worklet.ts served from
 * /worklet/pitch-processor.js (generated by `pnpm build:worklet`).
 */
import { BASE_PATH } from "@/basePath";

import type { PitchReading } from "./messages";

export type MicPitchStream = {
  context: AudioContext;
  /** Rough one-way input latency estimate in ms (capture + analysis window). */
  estimatedLatencyMs: number;
  stop: () => Promise<void>;
};

const WORKLET_URL = `${BASE_PATH}/worklet/pitch-processor.js`;
// Must match pitch-worklet.ts.
const WINDOW_SIZE = 2048;

export async function startMicPitchStream(
  onReading: (reading: PitchReading) => void
): Promise<MicPitchStream> {
  const stream = await navigator.mediaDevices.getUserMedia({
    audio: {
      // Speech processing distorts guitar signals — turn it all off.
      echoCancellation: false,
      noiseSuppression: false,
      autoGainControl: false,
    },
  });

  const context = new AudioContext({ latencyHint: "interactive" });
  await context.audioWorklet.addModule(WORKLET_URL);

  const source = context.createMediaStreamSource(stream);
  const pitchNode = new AudioWorkletNode(context, "pitch-processor", {
    numberOfInputs: 1,
    numberOfOutputs: 1,
    channelCount: 1,
  });
  pitchNode.port.onmessage = (event: MessageEvent<PitchReading>) => {
    onReading(event.data);
  };

  // A worklet only processes while it is pulled by the destination —
  // route it through a muted gain so nothing is audible (no feedback).
  const mute = context.createGain();
  mute.gain.value = 0;
  source.connect(pitchNode);
  pitchNode.connect(mute);
  mute.connect(context.destination);

  // Some browsers start the context suspended until a user gesture resumed it.
  if (context.state === "suspended") await context.resume();

  const estimatedLatencyMs =
    ((context.baseLatency ?? 0) + WINDOW_SIZE / context.sampleRate) * 1000;

  return {
    context,
    estimatedLatencyMs,
    stop: async () => {
      pitchNode.port.onmessage = null;
      source.disconnect();
      pitchNode.disconnect();
      mute.disconnect();
      stream.getTracks().forEach((track) => track.stop());
      await context.close();
    },
  };
}
